{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hwilliamgo",
    "module": "fastviewtree",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "n7azlrcglza7bevautpuk5hbxa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fastviewtree-1.0.6.aar",
          "url": "fastviewtree-1.0.6.aar",
          "size": 8125,
          "sha512": "e8a24c8919ecf9f070ebda9b12b2fbf1a51ac28a260413a4e464074cc5353c7c6ab5e3b4d724d1d9bd4d11b10aebdbca8500a04beee13600fb6ae0ffea9cccdd",
          "sha256": "a11cc879090cc3e42e5d4de316df5d001430604ba5ae4e96f18afc9abddacd6d",
          "sha1": "8d32c1b84e2052554e697e2ff41931859460308b",
          "md5": "304c85e6b2217feb87b7c6cf715c5a47"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "fastviewtree-1.0.6.aar",
          "url": "fastviewtree-1.0.6.aar",
          "size": 8125,
          "sha512": "e8a24c8919ecf9f070ebda9b12b2fbf1a51ac28a260413a4e464074cc5353c7c6ab5e3b4d724d1d9bd4d11b10aebdbca8500a04beee13600fb6ae0ffea9cccdd",
          "sha256": "a11cc879090cc3e42e5d4de316df5d001430604ba5ae4e96f18afc9abddacd6d",
          "sha1": "8d32c1b84e2052554e697e2ff41931859460308b",
          "md5": "304c85e6b2217feb87b7c6cf715c5a47"
        }
      ]
    }
  ]
}
